name: Update Dev Index

on:
  push:
    branches: [ main, master ]
    paths:
      - "src/**"
      - "server/**"
      - "backend/**"
      - "apps/**"
      - "puvi-frontend/**"
      - "puvi-backend/**"
      - ".dev-index/**"
      - ".github/workflows/update-dev-index.yml"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          
      - name: Install dev-index deps
        run: npm ci || npm i
        working-directory: .dev-index
        
      - name: Generate index
        run: npm run gen:index
        working-directory: .dev-index
        
      - name: Copy project_index.json to scripts directory
        run: |
          if [ -f ".dev-index/project_index.json" ]; then
            cp .dev-index/project_index.json .dev-index/scripts/
            echo "✓ Copied project_index.json to scripts directory"
          else
            echo "❌ project_index.json not found!"
            exit 1
          fi
          
      - name: Generate dependency matrix
        run: node scripts/build-dependency-matrix.mjs
        working-directory: .dev-index
        
      - name: Build feature packs
        run: node scripts/build-feature-packs.mjs
        working-directory: .dev-index
        
      - name: Move generated files to proper locations
        run: |
          # Move dependency files back to .dev-index root
          if [ -f ".dev-index/scripts/dependency-matrix.json" ]; then
            mv .dev-index/scripts/dependency-matrix.json .dev-index/
          fi
          if [ -f ".dev-index/scripts/DEPENDENCY-REPORT.md" ]; then
            mv .dev-index/scripts/DEPENDENCY-REPORT.md .dev-index/
          fi
          # Move packs directory to .dev-index root
          if [ -d ".dev-index/scripts/packs" ]; then
            mv .dev-index/scripts/packs .dev-index/
          fi
          
      - name: Debug - Check generated files
        run: |
          echo "=== Generated Files ==="
          echo "Contents of .dev-index directory:"
          ls -la .dev-index/
          echo ""
          if [ -d ".dev-index/packs" ]; then
            echo "Feature packs generated:"
            ls -la .dev-index/packs/
          fi
          if [ -f ".dev-index/DEPENDENCY-REPORT.md" ]; then
            echo "✓ Dependency report generated"
          fi
          
      - name: Commit all dev artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update dev index, feature packs, and dependency analysis"
          file_pattern: |
            .dev-index/project_index.json
            .dev-index/dependency-matrix.json
            .dev-index/DEPENDENCY-REPORT.md
            .dev-index/packs/*.md
          skip_dirty_check: false
          skip_fetch: false
          skip_checkout: false
          disable_globbing: false
          add_options: '-A'
